### ISSUE TITLE
Submodule referencing your plugin not finding commit

### ISSUE THREAD

**Issue by aquacode** [chr4/nginx.vim#11]
This is more of a question than it is an issue. I'm wondering if you might be able to help.
I'm attempting to use this .vim dotfiles repo: https://github.com/jessfraz/.vim
It references your plugin and the following commit:
https://github.com/chr4/nginx.vim/tree/a3def0ecd201de5ea7294cf92e4aba62775c9f5c
Yet, when I attempt to do:
`git submodule update --init` I get a failure of the following:
error: Server does not allow request for unadvertised object a3def0ecd201de5ea7294cf92e4aba62775c9f5c
Fetched in submodule path 'bundle/nginx.vim', but it did not contain a3def0ecd201de5ea7294cf92e4aba62775c9f5c. Direct fetching of that commit failed.
Any ideas?

**Comment by chr4** [comment]
Mmh, seems to me like this is not related to this repository, but rather some sort of error from either the dotfile configuration or a local issue. 

Maybe you have more luck asking https://github.com/jessfraz/.vim? 

Closing this. Feel free to re-open if this turns out to be something I can fix on this end.

**Comment by aquacode** [comment]
Right, I wasn't saying this repository had the problem, but I was hoping that perhaps you would be able to make sense of the issue. Apparently someone else figured it out. I guess this repo rebased master branch and thus the original linked commit doesn't exist anymore. That was all I was looking for.
