### ISSUE TITLE
"gzip on" is marked as an error

### ISSUE THREAD

**Issue by bdesham** [chr4/nginx.vim#8]
I’m not sure if this is an oversight or an intentional feature 😄 I tried adding the following directive to a `location` block:

    gzip on;

and the `on` was highlighted as an error. I notice that the syntax file includes

```
hi link ngxGzipOff ngxBoolean
hi link ngxGzipOn Error
````

I’m curious: why do you consider enabling gzip to be an error?

**Comment by chr4** [comment]
This is intentional. 

There's a vulnerability with gzip (which do not seem to be mitingated) called [BREACH](http://breachattack.com/).

To my knowledge there are workarounds to make the use of `gzip` safe, but they require additional nginx modules or have to be taken care of on the application side. One method would be to use [Chunked-Encoding](https://blog.qualys.com/ssllabs/2013/08/07/defending-against-the-breach-attack).

I think, as this requires additional efford the use of `gzip on` should be marked as dangerous to raise awareness that additional mitingations need to be applied.

**Comment by bdesham** [comment]
OK. Thank you for the explanation (and the great script!).
